(* https://docs.oracle.com/javase/specs/jls/se8/html/jls-19.html *)
(* Root Syntax Tree *)
CompilationUnit =
  ['FROM' Charanumerics] ['WHERE' Statement]
;

Statement =
  ConditionalExpression
;

ConditionalExpression = 
  ConditionalOrExpression
;

ConditionalOrExpression = 
  ConditionalAndExpression
  ConditionalOrExpression '||' ConditionalAndExpression
  ConditionalOrExpression '|' ConditionalAndExpression
;

ConditionalAndExpression = 
  EqualityExpression
  ConditionalAndExpression '&&' EqualityExpression
  ConditionalAndExpression '&' EqualityExpression
;

EqualityExpression =
  RelationalExpression
  EqualityExpression '==' RelationalExpression
  EqualityExpression '=' RelationalExpression
  EqualityExpression '!=' RelationalExpression
  EqualityExpression 'contains' RelationalExpression
  EqualityExpression 'containsWithIgnoreCase' RelationalExpression
  EqualityExpression 'startsWith' RelationalExpression
  EqualityExpression 'startsWithIgnoreCase' RelationalExpression
  EqualityExpression 'endsWith' RelationalExpression
  EqualityExpression 'endsWithIgnoreCase' RelationalExpression
;

RelationalExpression =
  AdditiveExpression
  RelationalExpression '<' AdditiveExpression
  RelationalExpression '<=' AdditiveExpression
  RelationalExpression '>' AdditiveExpression
  RelationalExpression '>=' AdditiveExpression
;

AdditiveExpression =
  MultiplicativeExpression
  AdditiveExpression '+' MultiplicativeExpression
  AdditiveExpression '-' MultiplicativeExpression
;

MultiplicativeExpression =
  Primary
  MultiplicativeExpression '*' Primary
  MultiplicativeExpression '/' Primary
  MultiplicativeExpression '%' Primary
;

Primary = 
  Literal
  '(' ConditionalExpression ')'
  Literal '.' Literal
  'true'
  'false'
  String
  Numeric
;